
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: user-center
# DataSource Config

  datasource:
    url: jdbc:mysql://localhost:3306/ice
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wang1998
    #session失效时间
  session:
    timeout: 86400
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: "`我是测试`,**你知道吗**
    # aaa"
    email: xiaoymin@foxmail.com
    concat: 1303971905@qq.com
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 用户模块
        api-rule: package
        api-rule-resources:
          - com.ice.usercenter.controller